version: '3'

services:
  bot:
    image: philingood/crazy-bot
    restart: unless-stopped
    env_file:
      - ./.env
    hostname: crazy-bot
    container_name: crazy-bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

