name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/crazy-bot:test

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Ruff
      uses: chartboost/ruff-action@v1

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "TEST=1" > .env
        echo "BOT_TOKEN_TEST=${{ secrets.BOT_TOKEN }}" >> .env
        echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt

    - name: Test
      run: |
        make test

  build-docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "TEST=1" > .env
        echo "BOT_TOKEN_TEST=${{ secrets.BOT_TOKEN }}" >> .env
        echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      shell: bash

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}

    - name: Test
      run: |
        docker run \
        --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --env-file .env \
        ${{ env.TEST_TAG }} \

