name: Deploy to Server

on:
  push:
    branches: [ "deploy" ]

permissions:
  contents: read

jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/crazy-bot:latest
#           file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
            ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} bash <<EOF
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crazy-bot
            sudo docker stop crazy-bot || true
            sudo docker rm crazy-bot || true
            sudo docker run --name crazy-bot --env-file /home/services/crazy-bot/.env --restart=unless-stopped -d ${{ secrets.DOCKERHUB_USERNAME }}/crazy-bot
            EOF
