name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/crazy-bot:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/crazy-bot:latest

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: docker run --rm ${{ env.TEST_TAG }}
